/**
 * Bibliothèque de sections proposée dans le studio (« Ajouter une section ») :
 * noms parlants, catégories, descriptions et exemple de réglages pour l'aperçu.
 * Les types viennent de theme-base/sections ; une section absente d'ici reste ajoutable sous son nom technique.
 * Textes affichés dans le studio : langue de l'interface (libraryEntry).
 */
import type { Lang } from "../i18n";

export type SectionCategory = "Ouverture" | "Produit" | "Preuves" | "Animations" | "Images et vidéos" | "Collections" | "Textes" | "Conversion" | "Avancé";

export type LibraryEntry = { type: string; name: string; category: SectionCategory; description: string; keywords?: string };

/** Noms, descriptions et mots-clés anglais (la catégorie reste la clé française, traduite par l'interface). */
const SECTION_LIBRARY_EN: Record<string, { name: string; description: string; keywords: string }> = {
  "hero-fullbleed": { name: "Main banner", description: "Large full-screen image or video, headline and button.", keywords: "hero home full screen banner" },
  "hero-split": { name: "Split banner", description: "Text on one side, product photo on the other.", keywords: "hero split banner" },
  "hero-editorial": { name: "Editorial banner", description: "Big two-line headline, magazine style.", keywords: "hero magazine editorial" },
  "hero": { name: "Hero", description: "Simple, clean opening banner: image or video, headline, text and button.", keywords: "hero banner opening simple" },
  "hero-flex": { name: "Premium hero — build your own", description: "Opening banner made of blocks you add and reorder: eyebrow, headline, buttons, badge, real rating, logos, key specs…", keywords: "hero banner blocks custom flexible rating logos" },
  "slideshow": { name: "Premium slideshow", description: "Full-frame image or video slides with text and buttons, fade or slide, autoplay with pause.", keywords: "slideshow slider carousel slides hero" },
  "day-night": { name: "Day / night experience", description: "One scene that switches between a day and a night mood, with a switch or as you scroll.", keywords: "day night switch toggle mood morning evening scroll" },
  "marquee": { name: "Scrolling banner", description: "Continuously scrolling text.", keywords: "marquee ticker scrolling" },
  "curved-marquee": { name: "Curved text", description: "Scrolling banner that follows a curve.", keywords: "marquee curve curved" },
  "routine-steps": { name: "Step-by-step routine", description: "The product stays on screen while the steps scroll by, with labels on the product.", keywords: "steps how to use scroll sticky routine" },
  "scroll-story": { name: "Product scroll story", description: "Product details appear as you scroll.", keywords: "scroll story details" },
  "stack-cards": { name: "Stacked cards", description: "Cards that stack up as you scroll.", keywords: "cards stack stacked" },
  "horizontal-gallery": { name: "Editorial scroll cards", description: "Horizontal carousel of illustrated cards.", keywords: "carousel horizontal gallery" },
  "stats": { name: "Animated key figures", description: "Verified figures that animate, with their source.", keywords: "figures statistics stats counter numbers" },
  "before-after": { name: "Before / After", description: "Sliding comparison between two images.", keywords: "comparison before after" },
  "testimonials": { name: "Premium customer reviews", description: "Real reviews you enter, shown as cards with rating and photo.", keywords: "reviews testimonials" },
  "product-reviews": { name: "Customer reviews (app)", description: "Placeholder for your reviews app (Judge.me, Loox…).", keywords: "reviews app" },
  "trust-bar": { name: "Trust badges", description: "Your real commitments: payment, returns, customer service.", keywords: "trust reassurance guarantees badges" },
  "features-grid": { name: "Benefits", description: "Grid of features with icons or images.", keywords: "features benefits advantages" },
  "image-with-text": { name: "Image with text", description: "An image and its explanation, side by side.", keywords: "image text" },
  "featured-product": { name: "Premium featured product", description: "A product with gallery, thumbnails and zoom, variant swatches, price, add to cart and key points.", keywords: "product featured buy gallery zoom variants swatches" },
  "product-360": { name: "360° product view", description: "Turn the product by dragging or scrolling, from an ordered series of photos.", keywords: "360 spin rotate 3d viewer product" },
  "how-to": { name: "How to use", description: "Numbered steps with image or video; the timeline fills as you scroll.", keywords: "how to use steps instructions tutorial guide" },
  "logo-list": { name: "Logos and partners", description: "Strip or grid of your real partners' logos, scrolling continuously if you like.", keywords: "logos partners brands press stockists marquee" },
  "shipping-journey": { name: "Shipping journey", description: "Order, packing, dispatch, delivery: your real lead times on an animated timeline.", keywords: "shipping delivery timeline steps lead time" },
  "visual-menu": { name: "Stories visual menu", description: "Round story-style shortcuts to your collections and pages, with an animated ring.", keywords: "stories menu circles navigation collections" },
  "customer-wall": { name: "Customer photo wall", description: "Masonry wall of photos and videos (shared with permission), with a lightbox.", keywords: "ugc customer photos wall masonry gallery lightbox instagram" },
  "newsletter-media": { name: "Newsletter with media", description: "Email sign-up with an image or video beside it or behind it, plus consent.", keywords: "newsletter email sign up subscribe video image consent" },
  "featured-offer": { name: "Featured offer", description: "Large centered offer: value, copyable promo code, validity and terms.", keywords: "offer promo discount code coupon sale" },
  "content-tabs": { name: "Content tabs", description: "Accessible tabs, each with rich text and an image.", keywords: "tabs content details information" },
  "legal-page": { name: "Legal page", description: "Readable terms, notices or policy layout with an automatic table of contents.", keywords: "legal terms conditions privacy policy notice table of contents" },
  "specs-list": { name: "Specifications", description: "Clear spec sheet in rows.", keywords: "specifications technical specs" },
  "situations": { name: "Situations", description: "\"Sound familiar?\": the moments when the product helps.", keywords: "situations problems use cases" },
  "timeline": { name: "Session timeline", description: "Timeline of numbered steps.", keywords: "timeline steps" },
  "video-showcase": { name: "Premium video", description: "Large video with a title, played on scroll.", keywords: "video" },
  "video-reels": { name: "UGC video carousel", description: "Vertical, social-media-style videos.", keywords: "reels ugc tiktok vertical videos" },
  "gallery-mosaic": { name: "Flexible collage", description: "Photo mosaic with mixed sizes.", keywords: "mosaic gallery collage" },
  "double-banner": { name: "Premium double banner", description: "Two large banners side by side (stacked on mobile), image or video, with a soft hover zoom.", keywords: "double banner two banners split promo" },
  "media-gallery": { name: "Premium media gallery", description: "Mixed grid of photos and videos, with a full-screen viewer.", keywords: "gallery media photos videos lightbox grid" },
  "social-gallery": { name: "Premium social gallery", description: "Social-media-style grid of your own photos and videos, with a \"Follow us\" link.", keywords: "social instagram tiktok ugc follow grid" },
  "editorial-gallery": { name: "Editorial gallery", description: "Asymmetric magazine-style layout, italic captions, subtle parallax.", keywords: "editorial gallery magazine lookbook parallax" },
  "story-circles": { name: "Story circles", description: "Round, stories-style thumbnails.", keywords: "stories circles" },
  "featured-collection": { name: "Featured collection", description: "A selection of products in a grid.", keywords: "collection products grid" },
  "collection-list": { name: "Premium collections", description: "Large image cards with the title on top: grid, asymmetric grid or carousel.", keywords: "collections categories collection list grid carousel" },
  "immersive-reviews": { name: "Immersive reviews", description: "One real review per full-frame card, over a photo or video, with gentle autoplay.", keywords: "reviews testimonials customer immersive carousel video verified" },
  "video-carousel": { name: "Premium video carousel", description: "Large 16:9 or 9:16 videos in a centered carousel, active one played muted with sound button.", keywords: "video carousel slider reels youtube vimeo" },
  "featured-blog": { name: "Premium featured blog", description: "Your latest blog articles as editorial cards, with date and reading time.", keywords: "blog articles news journal posts" },
  "countdown": { name: "Countdown", description: "Timer to a fixed date you set (offer, launch), with an end message.", keywords: "countdown timer offer sale launch deadline" },
  "alternating-content": { name: "Alternating content", description: "Image or video and text rows that switch sides, revealed on scroll.", keywords: "alternating image text rows zigzag video" },
  "rich-text": { name: "Editorial text", description: "A highlighted paragraph.", keywords: "text editorial" },
  "faq": { name: "Premium FAQ", description: "Animated accordion, optional question search, one or two columns, FAQ rich results.", keywords: "faq questions frequently asked accordion search" },
  "newsletter": { name: "Newsletter", description: "Sign-up to your emails.", keywords: "newsletter email sign up subscribe" },
  "cta-banner": { name: "Call-to-action banner", description: "A strong message and a button.", keywords: "call to action cta button" },
  "contact-form": { name: "Contact form", description: "Shopify contact form.", keywords: "contact form" },
  "wave-divider": { name: "Wave divider", description: "Wave transition between two sections.", keywords: "divider wave separator" },
  "custom-liquid": { name: "Custom Liquid", description: "Code for a widget or an app.", keywords: "code liquid html widget" },
  "apps": { name: "Apps", description: "Placeholder for an installed app's block.", keywords: "app apps" },
  "expert-endorsements": { name: "Verified professionals", description: "Recommendations from real professionals, quoted with their consent: photo, profession, quote and proof.", keywords: "experts professionals endorsements doctor recommended verified" },
  "brand-promise": { name: "Brand promise", description: "A bold promise with a highlighted word, your commitments with icons and a mood image.", keywords: "promise brand commitments values mission" },
  "precautions": { name: "Precautions", description: "Precautions for use and warnings from your instructions, clear and reassuring.", keywords: "precautions warnings safety instructions usage" },
  "product-recommendations": { name: "Product recommendations", description: "Carousel of products recommended by Shopify, with a fallback collection.", keywords: "recommendations related products carousel upsell cross-sell" },
  "reassurance": { name: "Reassurance", description: "Large guarantee cards (payment, delivery, returns, support) with your real terms and subtle animated icons.", keywords: "reassurance guarantees trust payment delivery returns support cards" },
  "animated-benefits": { name: "Animated benefits", description: "Product benefits revealed on scroll, with a line that draws itself and a step counter.", keywords: "benefits advantages scroll animated features" },
  "animated-story": { name: "Animated story", description: "Your brand story in chapters: text lights up as you scroll while the image changes.", keywords: "story brand chapters scroll about history" },
  "floating-scene": { name: "Floating product scene", description: "The cut-out product floats above a scene, with depth effects that follow the mouse and scroll.", keywords: "floating parallax product cut-out scene 3d hero" },
  "video-stories": { name: "Product video stories", description: "Story-style circles that open a full-screen vertical video player: progress bars, auto-advance, sound, swipe and keyboard.", keywords: "stories video vertical reels player circles instagram" },
  "creative-divider": { name: "Creative divider", description: "Transition between two sections: wave, diagonal, curve, zigzag or thin scrolling text, in the colors of the sections around it.", keywords: "divider separator wave diagonal curve zigzag marquee transition" },
  "comparison-table": { name: "Comparison table", description: "\"Us vs. alternatives\" table with check marks, crosses or text and a highlighted column; scrolls sideways on mobile.", keywords: "comparison table versus vs alternatives competitors check" },
  "animated-text": { name: "Premium animated text", description: "Large typographic statement: words that appear, moving gradient, highlight on scroll or a rotating word.", keywords: "animated text typography statement gradient rotating words highlight" },
  "immersive-video": { name: "Immersive video", description: "A video that grows from a rounded card to full screen as you scroll, with overlay text and sound.", keywords: "video immersive full screen scroll expand zoom cinematic" },
  "editorial-visual": { name: "Editorial visual", description: "Large magazine-style image with a caption card, offset text and a zoomed-in detail.", keywords: "editorial magazine image caption detail zoom lookbook" },
  "exploded-view": { name: "Animated exploded view", description: "Detail points you place on the product image spread out on scroll, with labels linked by lines.", keywords: "exploded view hotspots details features callouts product scroll" },
  "about": { name: "About", description: "Complete about section: big headline, image, why you exist, your commitment and value cards.", keywords: "about us brand story values mission commitment" },
  "scroll-steps": { name: "Scroll steps", description: "Pinned steps that change as you scroll: number, title, text and a media that swaps.", keywords: "steps scroll pinned sticky how it works process" },
};

/** Entrée de la bibliothèque dans la langue de l'interface. */
export function libraryEntry(type: string, lang: Lang): LibraryEntry | undefined {
  const e = SECTION_LIBRARY.find((x) => x.type === type);
  const en = SECTION_LIBRARY_EN[type];
  return e && lang === "en" && en ? { ...e, ...en } : e;
}

export const SECTION_LIBRARY: LibraryEntry[] = [
  { type: "hero-fullbleed", name: "Bannière principale", category: "Ouverture", description: "Grande image ou vidéo plein écran, titre et bouton.", keywords: "héros hero accueil plein écran" },
  { type: "hero-split", name: "Bannière divisée", category: "Ouverture", description: "Texte d'un côté, photo du produit de l'autre.", keywords: "héros hero split" },
  { type: "hero-editorial", name: "Bannière éditoriale", category: "Ouverture", description: "Grand titre sur deux lignes, style magazine.", keywords: "héros hero magazine" },
  { type: "hero", name: "Hero", category: "Ouverture", description: "Bannière d'ouverture simple et propre : image ou vidéo, titre, texte et bouton.", keywords: "héros hero bannière ouverture simple" },
  { type: "hero-flex", name: "Hero premium — ajout libre", category: "Ouverture", description: "Bannière d'ouverture en blocs à ajouter et ordonner : surtitre, titre, boutons, badge, note réelle, logos, caractéristiques…", keywords: "héros hero blocs libre modulable note logos" },
  { type: "slideshow", name: "Diaporama premium", category: "Ouverture", description: "Diapositives plein cadre image ou vidéo, texte et boutons, fondu ou glissé, lecture auto avec pause.", keywords: "diaporama slider carrousel diapositives slideshow" },
  { type: "day-night", name: "Expérience jour / nuit", category: "Animations", description: "Une scène qui bascule entre une ambiance jour et nuit, par interrupteur ou au défilement.", keywords: "jour nuit interrupteur ambiance matin soir défilement" },
  { type: "marquee", name: "Bandeau défilant", category: "Animations", description: "Texte qui défile en continu.", keywords: "marquee défilement" },
  { type: "curved-marquee", name: "Texte en courbe", category: "Animations", description: "Bandeau défilant qui suit une courbe.", keywords: "marquee courbe" },
  { type: "routine-steps", name: "Routine en gestes", category: "Animations", description: "Le produit reste à l'écran pendant que les gestes défilent, avec étiquettes sur le produit.", keywords: "étapes mode d'emploi utilisation scroll sticky routine" },
  { type: "scroll-story", name: "Défilement produit", category: "Animations", description: "Les détails du produit apparaissent au fil du défilement.", keywords: "scroll histoire" },
  { type: "stack-cards", name: "Cartes empilées", category: "Animations", description: "Cartes qui s'empilent au défilement.", keywords: "cartes empilées stack" },
  { type: "horizontal-gallery", name: "Cartes scroll éditorial", category: "Animations", description: "Carrousel horizontal de cartes illustrées.", keywords: "carrousel horizontal" },
  { type: "stats", name: "Chiffres clés animés", category: "Preuves", description: "Chiffres vérifiés qui s'animent, avec leur source.", keywords: "chiffres statistiques compteur" },
  { type: "before-after", name: "Avant / Après", category: "Preuves", description: "Comparaison glissante entre deux images.", keywords: "comparaison avant après" },
  { type: "testimonials", name: "Avis clients premium", category: "Preuves", description: "Vrais avis saisis par vous, en cartes avec note et photo.", keywords: "avis témoignages reviews" },
  { type: "immersive-reviews", name: "Avis clients immersifs", category: "Preuves", description: "Un vrai avis par grande carte plein cadre, sur photo ou vidéo, avec défilement automatique doux.", keywords: "avis témoignages clients immersif carrousel vidéo vérifié reviews testimonials" },
  { type: "product-reviews", name: "Avis clients (application)", category: "Preuves", description: "Emplacement pour votre application d'avis (Judge.me, Loox…).", keywords: "avis reviews application" },
  { type: "trust-bar", name: "Arguments de confiance", category: "Preuves", description: "Vos engagements réels : paiement, retours, service client.", keywords: "confiance réassurance garanties" },
  { type: "features-grid", name: "Bénéfices", category: "Produit", description: "Grille d'atouts avec icônes ou images.", keywords: "atouts avantages bénéfices" },
  { type: "image-with-text", name: "Image et texte", category: "Produit", description: "Une image et son explication, côte à côte.", keywords: "image texte" },
  { type: "featured-product", name: "Produit vedette premium", category: "Produit", description: "Un produit avec galerie, vignettes et zoom, variantes en pastilles, prix, ajout au panier et points forts.", keywords: "produit vedette achat galerie zoom variantes pastilles" },
  { type: "product-360", name: "Produit à 360°", category: "Produit", description: "Faites tourner le produit au glisser ou au défilement, à partir d'une suite de photos.", keywords: "360 rotation tourner 3d visionneuse produit" },
  { type: "how-to", name: "Mode d'emploi", category: "Produit", description: "Étapes numérotées avec image ou vidéo ; la frise se remplit au défilement.", keywords: "mode d'emploi étapes utilisation notice tutoriel" },
  { type: "logo-list", name: "Logos et partenaires", category: "Preuves", description: "Bande ou grille des logos de vos vrais partenaires, en défilement continu si vous le souhaitez.", keywords: "logos partenaires marques presse revendeurs" },
  { type: "shipping-journey", name: "Parcours de livraison", category: "Preuves", description: "Commande, préparation, expédition, livraison : vos délais réels sur une frise animée.", keywords: "livraison expédition délais frise étapes" },
  { type: "visual-menu", name: "Menu visuel stories", category: "Collections", description: "Raccourcis ronds façon stories vers vos collections et pages, avec anneau animé.", keywords: "stories menu cercles navigation collections" },
  { type: "customer-wall", name: "Mur d'images clients", category: "Images et vidéos", description: "Mur en maçonnerie de photos et vidéos (partagées avec accord), avec visionneuse.", keywords: "ugc photos clients mur maçonnerie galerie instagram" },
  { type: "newsletter-media", name: "Newsletter avec média", category: "Conversion", description: "Inscription e-mail avec image ou vidéo à côté ou en fond, et consentement.", keywords: "newsletter email inscription vidéo image consentement" },
  { type: "featured-offer", name: "Offre centrale", category: "Conversion", description: "Grande offre centrée : valeur, code promo copiable, validité et conditions.", keywords: "offre promo remise code réduction soldes" },
  { type: "content-tabs", name: "Onglets de contenu", category: "Textes", description: "Onglets accessibles, chacun avec texte riche et image.", keywords: "onglets contenu détails informations" },
  { type: "legal-page", name: "Page légale", category: "Textes", description: "Mise en page lisible pour CGV, mentions ou politique, avec sommaire automatique.", keywords: "légal cgv mentions légales confidentialité politique sommaire" },
  { type: "specs-list", name: "Caractéristiques", category: "Produit", description: "Fiche technique claire en lignes.", keywords: "caractéristiques technique specs" },
  { type: "situations", name: "Situations", category: "Produit", description: "« Vous vous reconnaissez ? » : les moments où le produit aide.", keywords: "situations problèmes usages" },
  { type: "timeline", name: "Chronologie d'une séance", category: "Produit", description: "Frise d'étapes numérotées.", keywords: "frise étapes chronologie" },
  { type: "video-showcase", name: "Vidéo premium", category: "Images et vidéos", description: "Grande vidéo avec titre, lue au défilement.", keywords: "vidéo" },
  { type: "video-reels", name: "Carrousel vidéos UGC", category: "Images et vidéos", description: "Vidéos verticales façon réseaux sociaux.", keywords: "reels ugc tiktok vidéos verticales" },
  { type: "video-carousel", name: "Carrousel vidéo premium", category: "Images et vidéos", description: "Grandes vidéos 16:9 ou 9:16 en carrousel centré, la vidéo active lue en muet avec bouton son.", keywords: "vidéo carrousel slider reels youtube vimeo video carousel" },
  { type: "alternating-content", name: "Contenus alternés", category: "Images et vidéos", description: "Rangées image ou vidéo et texte qui changent de côté, révélées au défilement.", keywords: "alterné image texte rangées zigzag vidéo alternating" },
  { type: "gallery-mosaic", name: "Collage modulable", category: "Images et vidéos", description: "Mosaïque de photos aux tailles variées.", keywords: "mosaïque galerie collage" },
  { type: "double-banner", name: "Double bannière premium", category: "Images et vidéos", description: "Deux grandes bannières côte à côte (empilées sur mobile), image ou vidéo, zoom doux au survol.", keywords: "double bannière deux bannières promo" },
  { type: "media-gallery", name: "Galerie média premium", category: "Images et vidéos", description: "Grille mixte de photos et vidéos, avec visionneuse plein écran.", keywords: "galerie média photos vidéos visionneuse grille lightbox" },
  { type: "social-gallery", name: "Galerie sociale premium", category: "Images et vidéos", description: "Grille façon réseaux sociaux avec vos propres photos et vidéos, et un lien « Suivez-nous ».", keywords: "réseaux sociaux instagram tiktok ugc suivez-nous grille" },
  { type: "editorial-gallery", name: "Galerie éditoriale", category: "Images et vidéos", description: "Composition asymétrique façon magazine, légendes en italique, parallaxe légère.", keywords: "galerie éditoriale magazine lookbook parallaxe" },
  { type: "story-circles", name: "Cercles stories", category: "Images et vidéos", description: "Pastilles rondes façon stories.", keywords: "stories cercles" },
  { type: "featured-collection", name: "Collection en vedette", category: "Collections", description: "Une sélection de produits en grille.", keywords: "collection produits grille" },
  { type: "collection-list", name: "Collections premium", category: "Collections", description: "Grandes cartes image avec titre en surimpression : grille, grille asymétrique ou carrousel.", keywords: "collections catégories liste de collections grille carrousel" },
  { type: "rich-text", name: "Texte éditorial", category: "Textes", description: "Un paragraphe mis en valeur.", keywords: "texte éditorial" },
  { type: "featured-blog", name: "Blog en vedette premium", category: "Textes", description: "Vos derniers articles de blog en cartes éditoriales, avec date et temps de lecture.", keywords: "blog articles actualités journal blog posts" },
  { type: "faq", name: "FAQ premium", category: "Textes", description: "Accordéon animé, recherche dans les questions, une ou deux colonnes, données structurées FAQ.", keywords: "faq questions fréquentes accordéon recherche" },
  { type: "newsletter", name: "Newsletter", category: "Conversion", description: "Inscription à vos e-mails.", keywords: "newsletter email inscription" },
  { type: "cta-banner", name: "Bannière d'appel", category: "Conversion", description: "Un message fort et un bouton.", keywords: "appel action cta bouton" },
  { type: "countdown", name: "Compte à rebours", category: "Conversion", description: "Minuteur jusqu'à une date fixe que vous réglez (offre, lancement), avec message de fin.", keywords: "compte à rebours minuteur offre promotion lancement countdown timer" },
  { type: "contact-form", name: "Formulaire de contact", category: "Conversion", description: "Formulaire de contact Shopify.", keywords: "contact formulaire" },
  { type: "wave-divider", name: "Vague de séparation", category: "Avancé", description: "Transition en vague entre deux sections.", keywords: "séparateur vague" },
  { type: "custom-liquid", name: "Liquid personnalisé", category: "Avancé", description: "Code d'un widget ou d'une application.", keywords: "code liquid html widget" },
  { type: "apps", name: "Applications", category: "Avancé", description: "Emplacement pour le bloc d'une application installée.", keywords: "application app" },
  { type: "expert-endorsements", name: "Professionnels vérifiés", category: "Preuves", description: "Recommandations de professionnels réels, cités avec leur accord : photo, profession, citation et preuve.", keywords: "experts professionnels recommandations médecin vérifié" },
  { type: "brand-promise", name: "Promesse", category: "Textes", description: "Une promesse forte avec mot d'accent, vos engagements illustrés et une image d'ambiance.", keywords: "promesse marque engagements valeurs mission" },
  { type: "precautions", name: "Précautions", category: "Produit", description: "Précautions d'emploi et avertissements de votre notice, lisibles et rassurants.", keywords: "précautions avertissements sécurité notice utilisation" },
  { type: "product-recommendations", name: "Recommandations produit", category: "Collections", description: "Carrousel des produits recommandés par Shopify, avec une collection de repli.", keywords: "recommandations produits associés carrousel vente croisée" },
  { type: "reassurance", name: "Réassurance", category: "Preuves", description: "Grandes cartes de garanties (paiement, livraison, retours, service client) avec vos vraies conditions et des icônes animées.", keywords: "réassurance garanties confiance paiement livraison retours service client cartes" },
  { type: "animated-benefits", name: "Bénéfices animés", category: "Animations", description: "Les bénéfices du produit se révèlent au défilement, avec un trait qui se dessine et un compteur d'étapes.", keywords: "bénéfices atouts avantages scroll animation" },
  { type: "animated-story", name: "Histoire animée", category: "Animations", description: "Votre histoire en chapitres : le texte s'allume au défilement pendant que l'image change.", keywords: "histoire marque chapitres scroll à propos récit" },
  { type: "floating-scene", name: "Scène visuelle flottante", category: "Images et vidéos", description: "Le produit détouré flotte au-dessus d'une scène, avec des effets de profondeur à la souris et au défilement.", keywords: "flottant parallaxe produit détouré scène 3d héros" },
  { type: "video-stories", name: "Stories vidéo produit", category: "Images et vidéos", description: "Cercles façon stories qui ouvrent un lecteur vidéo vertical plein écran : progression, enchaînement, son, glisser et clavier.", keywords: "stories vidéo verticale reels lecteur cercles instagram" },
  { type: "creative-divider", name: "Séparateur créatif", category: "Avancé", description: "Transition entre deux sections : vague, diagonale, courbe, zigzag ou fin texte défilant, aux couleurs des sections voisines.", keywords: "séparateur vague diagonale courbe zigzag bandeau transition" },
  { type: "comparison-table", name: "Tableau comparatif", category: "Produit", description: "Tableau « nous / alternatives » avec coches, croix ou texte et colonne mise en avant ; défilement horizontal sur mobile.", keywords: "comparatif tableau comparaison versus alternatives concurrents" },
  { type: "animated-text", name: "Texte animé premium", category: "Textes", description: "Grand texte typographique : mots qui apparaissent, dégradé qui se déplace, surlignage au défilement ou mot qui change.", keywords: "texte animé typographie manifeste dégradé mot qui change surlignage" },
  { type: "immersive-video", name: "Vidéo immersive", category: "Images et vidéos", description: "La vidéo passe d'une carte arrondie au plein écran au fil du défilement, avec texte en surimpression et son.", keywords: "vidéo immersive plein écran défilement agrandissement cinéma" },
  { type: "editorial-visual", name: "Visuel éditorial", category: "Images et vidéos", description: "Grande image façon magazine avec cartel, texte décalé et détail zoomé.", keywords: "éditorial magazine image cartel légende détail zoom lookbook" },
  { type: "exploded-view", name: "Vue éclatée animée", category: "Produit", description: "Les points de détail placés sur l'image du produit s'écartent au défilement, avec légendes reliées par des traits.", keywords: "vue éclatée points détails caractéristiques légendes produit défilement" },
  { type: "about", name: "À propos", category: "Textes", description: "Section « à propos » complète : grand titre, image, raison d'être, engagement et valeurs en cartes.", keywords: "à propos marque histoire valeurs mission engagement qui sommes-nous" },
  { type: "scroll-steps", name: "Étapes au défilement", category: "Animations", description: "Étapes épinglées qui changent au défilement : numéro, titre, texte et média qui se remplace.", keywords: "étapes défilement épinglé sticky comment ça marche processus" },
];

export const SECTION_CATEGORIES: SectionCategory[] = ["Ouverture", "Produit", "Preuves", "Animations", "Images et vidéos", "Collections", "Textes", "Conversion", "Avancé"];

/** Sections qui ne s'ajoutent pas depuis la bibliothèque (structure de page, gabarits). */
export const NOT_ADDABLE = new Set(["header", "footer", "announcement-bar", "cart-drawer"]);
export const addable = (type: string) => !type.startsWith("main-") && !NOT_ADDABLE.has(type);
